docs: add user guides for use grpc basic auth
pactus-project/pactus.org pull request #193
Opened 2024-03-13 08:27 UTC by Ja7ad

2024-03-14 06:22 UTC, Ja7ad commented
@Mr-HoDL58 @b00f I fixed errors, please review this post.

2024-03-16 06:02 UTC, b00f requested changes

2024-03-16 06:02 UTC, b00f commented on website/_i18n/zh/user-guides/grpc-basic-auth/index.md
> +htpasswd -bnBC 10 javad mypassword
```suggestion
htpasswd -bnBC 10 user pass
```

2024-03-16 06:02 UTC, b00f commented on website/_i18n/en/user-guides/grpc-basic-auth/index.md
> +htpasswd -bnBC 10 javad mypassword
```suggestion
htpasswd -bnBC 10 user pass
```

2024-03-16 06:02 UTC, b00f commented on website/_i18n/zh/user-guides/grpc-basic-auth/index.md
> +htpasswd -bnBC 10 javad mypassword
```suggestion
htpasswd -bnBC 10 user pass
```

2024-03-16 06:02 UTC, b00f commented on website/_i18n/ar/user-guides/grpc-basic-auth/index.md
> +htpasswd -bnBC 10 javad mypassword
```suggestion
htpasswd -bnBC 10 user pass
```

2024-03-16 06:49 UTC, Ja7ad commented
@b00f I fix all things

2024-03-16 09:19 UTC, b00f approved these changes

2024-03-16 09:19 UTC, merged